### ISSUE TITLE
battery status when not charging

### ISSUE THREAD

**Issue by Bimoaryo5** [doanhmaple/Asus-ROG-Strix-GL503GE-Hackintosh#1]
hello, i want to ask
the battery status when laptop not charging some times show charging so how to fix this ?
and why some times the cpu hotter than windows ? just ask for this 

btw thanks for your guide almost perfect all features work on my gl503ge 
i use wifi AirportItlwm from openintelwireless and wifi work fully function but just speed still not stable
and i found tutorial to make backlight rgb rog on hackintosh work

**Comment by doanhxd** [comment]
1. Thank you for reporting, about the battery status when not charging... i'm not tested yet but i will try again later on my friend laptop. the ASUS GL503GE is my friend laptop and his battery life is bad and he doesn't mind it so i just use the VirtualSMC plugin to show the status :D...

2. About CPU hotter than Windows, it's very normal even on the real MacBook, the CPU always work at highest performance (see it before), and on my Razer Blade 15 (i7-8750H too) it's hotter than Windows too :D, you can try using one-key-cpufriend (CPUFriend kexts)... 


3. Thanks for using my guide again (actualy it's not a guide, it just a repo i've created for saving which laptop i was Hackintosh on :D), haha :D and about intel wifi card, just give OpenIntelWireless team more time to complete it :D

**Comment by Bimoaryo5** [comment]
thanks for answering it 
VirtualSMC plugin just show it not my real battery percent ?
ok i will try to use cpufriend i think in efi folder cpufriend kext already add, so how to use one key cpufriend ? or i already use it ? 
yes i already use openintelwireless and work

but your repo almost perfect well in gl503 almost no error just little more tweaks

and sorry for my bad english

**Comment by doanhxd** [comment]
I think VirtualSMC plugins is for many devices and maybe not give you exactly the result you want... i've never have to SSDT patch another laptop battery before (because almost laptop doesn't need to do that) so if i have chance i'll research it if i met my friend and borrow his laptop again to find the way to fix it :D 

Hmm i see, if the CPUFriend kexts already in the EFI folder, so you just have to open config.plist and Enable those 2 kexts (CPUFriend.kext + CPUFriendDataProvider.kext) in 'Kernel' tab :D

**Comment by doanhxd** [comment]
Hmm i just check the repo again and i'm not see the CPUFriend kexts there :v, just follow this guide to have them :D 

https://github.com/stevezhengshiqi/one-key-cpufriend

**Comment by Bimoaryo5** [comment]
ok thanks for i try tht guides i hope this will fix 
and one more think why when i boot at apple logo got glitch like tht than normal again ?
![image](https://user-images.githubusercontent.com/22141543/97770941-78acb580-1b6a-11eb-98d2-8509739b4300.jpg)

**Comment by Bimoaryo5** [comment]
picture just example

**Comment by doanhxd** [comment]
hmm, I've never met this before ~~ sorry

**Comment by Bimoaryo5** [comment]
its ok 
btw
i test fn button not function ? or actually function ? why on me not function

sry if i ask too much 
thanks for answering

**Comment by doanhxd** [comment]
I have to idea with Fn + F1-12 button, I'm using Karabiner for those functions for GL503GE ~~

**Comment by Bimoaryo5** [comment]
its ok i use https://github.com/black-dragon74/ROG-HID and fn button work flawlessly :)
