### ISSUE TITLE
Unable to use HDMI output to monitor - Big Sur

### ISSUE THREAD

**Issue by ibnuh** [doanhmaple/Asus-ROG-Strix-GL503GE-Hackintosh#2]
Hi Doanh,

First of all thanks for creating this guide and providing the OpenCore configs, I've tried it with little to no changes to the file provided by this repo, and everything seems to works just fine except the HDMI port.

When I connect plugged in the HDMI, the mouse cursor just kinda laggy and the monitor couldn't detect any signal. 

Things I have tried:
- Changing the `SystemProductName` to: `iMacPro1,1`, `iMac19,2`, `iMac19,3`

System specs:
- System Version: macOS 11.1 (20C69)

Questions:
1. My iGPU memory seems to be lower than yours from the README, could it be a different gl503ge version?

![image](https://user-images.githubusercontent.com/18393879/103354995-a7e69100-4adf-11eb-83fc-050f54b795ee.png)

Thanks in advance!

**Comment by ibnuh** [comment]
System Information dump

[gl503ge.txt](https://github.com/doanhmaple/Asus-ROG-Strix-GL503GE-Hackintosh/files/5754381/gl503ge.txt)

**Comment by doanhxd** [comment]
You should find another way to patching the iGPU and HDMI port, GL503GE is my friend laptop and i'm not see him for 2 month, last time I made him this EFI, I've change something about iGPU patch but i'm not remember now...

It's not problem about SMBios, The SystemProduct i putted is most stable for GL503GE,... 

iGPU Memory just for cosmetic, it'll not give you more performance, i just set it for fun

**Comment by doanhxd** [comment]
don't try to change SystemProductName lol, it'll not help you to fix anything

**Comment by ibnuh** [comment]
ah ok 😅 , I will keep looking for fixes and will update here, thanks!

**Comment by doanhxd** [comment]
thanks for seeing my repo ^^, I'll try to contact my friend tomorrow to borrow his laptop to check again about iGPU patch and update my repo soon ^^
